### ISSUE TITLE
FATAL Exception: GLThread

### ISSUE THREAD

**Issue by tyrannotorus** [tommyettinger/colorful-gdx#1]
I'm looking forward to getting this running, but I'm getting this error on construction of new ColorfulBatch() targeting android. Is there something I don't know or may be doing wrong at the outset?

EDIT: It turns out that just _including_ `api 'com.github.tommyettinger:colorful:0.5.0'` in my dependencies causes the issue even in the regular SpriteBatch.

```
2021-02-08 13:25:03.161 7790-7918/com.tyrannotorus E/AndroidRuntime: FATAL EXCEPTION: GLThread 45631
    Process: com.tyrannotorus, PID: 7790
    java.lang.AbstractMethodError: abstract method "java.lang.String com.badlogic.gdx.graphics.GL20.glGetActiveAttrib(int, int, java.nio.IntBuffer, java.nio.IntBuffer)"
        at com.badlogic.gdx.graphics.glutils.ShaderProgram.fetchAttributes(ShaderProgram.java:841)
        at com.badlogic.gdx.graphics.glutils.ShaderProgram.<init>(ShaderProgram.java:169)
        at com.github.tommyettinger.colorful.rgb.ColorfulBatch.createDefaultShader(ColorfulBatch.java:181)
        at com.github.tommyettinger.colorful.rgb.ColorfulBatch.<init>(ColorfulBatch.java:130)
        at com.github.tommyettinger.colorful.rgb.ColorfulBatch.<init>(ColorfulBatch.java:83)
        at com.tyrannotorus.world.World.<init>(World.java:36)
        at com.tyrannotorus.Main.create(Main.java:72)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:310)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1555)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```

**Comment by tommyettinger** [comment]
Agh! I'm not sure what's happening here; I've never seen a `java.lang.AbstractMethodError` before. This seems similar to a known bug in libGDX 1.9.14, though maybe not the same. The last line in ColorfulBatch that this traces through before going into libGDX is just
```java
        ShaderProgram shader = new ShaderProgram(vertexShader, fragmentShader);
```
where vertexShader and fragmentShader are already-assembled Strings. After that, line 841 of libGDX's ShaderProgram is just
```java
String name = Gdx.gl20.glGetActiveAttrib(program, i, params, type);
```
and I don't really understand why that fails, especially since every shader should call fetchAttributes() at some point and go through that line. I'll ask around about this AbstractMethodError; if you're using libGDX 1.9.14, I'd downgrade to 1.9.13 because of some strange bugs that slipped into the release (or upgrade to 1.9.15-SNAPSHOT).

I haven't tested on Android yet, but I guess this means I'm about to start. I hope I can find something!

**Comment by tommyettinger** [comment]
Well, this bug isn't showing up when running the latest [ColorfulDemo](https://github.com/yellowstonegames/SquidLib-Demos/tree/master/ColorfulDemo) on my Samsung S10e phone. I tried with libGDX 1.9.13 and 1.9.14, and neither had issues (1.9.14 has bigger problems with 3D, but the demo I used is 2D only). If you want to pop in and get some wider feedback on the libGDX Discord, [here's the link](https://discord.gg/NFBYHy72XB), my username is TEttinger and my current nick contains TEttinger. I'm thinking there could be a way colorful-gdx is involved here, but the rarity of this type of error (not even an Exception) has me thinking it's some Android quirk.

**Comment by tyrannotorus** [comment]
For the record, I was still on `libgdx 1.9.10`.
Upgrading to `libgdx 1.9.13` solved the problem.

Thanks for replying Tommy! I've joined the discord :)

**Comment by tommyettinger** [comment]
Hooray! Thanks also to crykn/damios, who was able to diagnose this:
> The method signature for `GL20#glGetActiveUniform` was changed in 1.9.11. This leads to issues if the gdx Android dependency is < 1.9.11 and the gdx core >= 1.9.11, the latter of which is probably caused by including colorful-gdx.

I think you had already fixed it by updating, but I'm glad I know what caused this.
