### ISSUE TITLE
RGB ColorfulBatch drawing black textures

### ISSUE THREAD

**Issue by deadpixelsociety** [tommyettinger/colorful-gdx#2]
I'm seeing an issue in my personal project where the RGB ColorfulBatch is drawing textures as all black no matter what parameters I use. I double checked with the RGB demo tests utilizing ColorfulBatch in this repository and receive the same issue.

[Image Example](https://i.imgur.com/iakAH4M.png)

**Comment by tommyettinger** [comment]
Looking into this now. The RGB ColorfulBatch is always a bit of an outlier because it doesn't use the same type of shader, so some bug may have snuck in. What version of colorful-gdx are you using?

**Comment by tommyettinger** [comment]
OK, I think I narrowed this down to a place where a negative value in the shader could occur, and it was raised to the 1.4 power, which is probably undefined/GPU-specific behavior. Thankfully, the other ColorfulBatch implementations had a different approach, and I was able to make some small changes to that better approach. Now, the RGB ColorfulBatch should look like this with neutral color and tweak at left, and the original at right: ![RGB ColorfulBatch Mona Lisa](https://i.imgur.com/XVjsiQO.png)

If you want to try this out, you've already got the repository and can run from source, so the latest commit should be all you need (it's a roughly 2-line change). Otherwise, you can use JitPack: https://jitpack.io/#tommyettinger/colorful-gdx/4da0721c9e

**Comment by deadpixelsociety** [comment]
Looks good, issue resolved.
